# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: weather_scheduler

on:
  push:
    branches: [ main ]
  schedule:
    # Runs at 5 minutes past every hour
    - cron: '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set Timezone to KST
      run: echo "TZ=Asia/Seoul" >> $GITHUB_ENV

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go 1.22.1
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'
      id: go

    - name: Load dependencies
      run: go mod download

    - name: tidy dependencies
      run: go mod tidy

    - name: Run the Go program
      env:
        SECRET_APIKEY: ${{ secrets.SECRET_APIKEY }}
        KAFKA_BOOTSTRAP_SERVER : ${{ secrets.KAFKA_BOOTSTRAP }}
      run: go run .

