# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Weather Data Scheduler

on:
  schedule:
    # Runs at 5 minutes past every hour
    - cron: '27 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go 1.22.1
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'
      id: go

    - name: Create secret directory
      run: mkdir -p ./secret

    - name: Create apikey file
      run: echo "${{ secrets.SECRET_APIKEY }}" > ./secret/apikey
      shell: bash

    - name: Create bootstrap.servers file
      run: echo "${{ secrets.KAFKA_BOOTSTRAP }}" > ./secret/bootstrap.servers
      shell: bash

    - name: Load dependencies
      run: go mod download

    - name: Run the Go program
      run: go run .

